/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package platihan;

/**
 *
 * @author KomangRyan
 */
import java.awt.Color;
import javax.swing.*;
import javax.swing.JOptionPane;

public class formMobil extends javax.swing.JFrame {
     mobilTransport a = new mobilTransport();
     
              

  
    
    /**
     * Creates new form formMobil
     */
    public formMobil() {
        initComponents();
     
    lgigi.setText("N");
    btnOff.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lmesin = new javax.swing.JLabel();
        lgas = new javax.swing.JLabel();
        lgigi = new javax.swing.JLabel();
        lrem = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lac = new javax.swing.JLabel();
        ltape = new javax.swing.JLabel();
        ltv = new javax.swing.JLabel();
        tAC = new javax.swing.JToggleButton();
        tTape = new javax.swing.JToggleButton();
        tTV = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        btnOn = new javax.swing.JButton();
        btnOff = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnPlusGigi = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnMinusGigi = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        trem = new javax.swing.JToggleButton();
        tgas = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setForeground(new java.awt.Color(0, 51, 153));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Status Mesin :");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gigi : ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gas : ");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rem : ");

        lmesin.setBackground(new java.awt.Color(255, 255, 255));
        lmesin.setForeground(new java.awt.Color(255, 255, 255));
        lmesin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lgas.setBackground(new java.awt.Color(255, 255, 255));
        lgas.setForeground(new java.awt.Color(255, 255, 255));
        lgas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lgigi.setBackground(new java.awt.Color(255, 255, 255));
        lgigi.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        lgigi.setForeground(new java.awt.Color(255, 255, 255));
        lgigi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgigi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lrem.setBackground(new java.awt.Color(255, 255, 255));
        lrem.setForeground(new java.awt.Color(255, 255, 255));
        lrem.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lmesin, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lgigi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lgas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lrem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lmesin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lgigi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lgas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lrem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("AC :");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tape :");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TV :");

        lac.setBackground(new java.awt.Color(255, 255, 255));
        lac.setForeground(new java.awt.Color(255, 255, 255));
        lac.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ltape.setBackground(new java.awt.Color(255, 255, 255));
        ltape.setForeground(new java.awt.Color(255, 255, 255));
        ltape.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ltv.setBackground(new java.awt.Color(255, 255, 255));
        ltv.setForeground(new java.awt.Color(255, 255, 255));
        ltv.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tAC.setBackground(new java.awt.Color(204, 0, 0));
        tAC.setForeground(new java.awt.Color(255, 255, 255));
        tAC.setText("I          O");
        tAC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tACMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tACMouseReleased(evt);
            }
        });
        tAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tACActionPerformed(evt);
            }
        });

        tTape.setBackground(new java.awt.Color(204, 0, 0));
        tTape.setForeground(new java.awt.Color(255, 255, 255));
        tTape.setText("I          O");
        tTape.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tTapeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tTapeMouseReleased(evt);
            }
        });
        tTape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTapeActionPerformed(evt);
            }
        });

        tTV.setBackground(new java.awt.Color(204, 0, 0));
        tTV.setForeground(new java.awt.Color(255, 255, 255));
        tTV.setText("I          O");
        tTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tTVMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tTVMouseReleased(evt);
            }
        });
        tTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ltv, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tTV, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lac, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(tAC, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ltape, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tTape, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lac, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tAC)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(ltape, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tTape))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(ltv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTV))
                .addGap(16, 16, 16))
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        btnOn.setBackground(new java.awt.Color(102, 255, 0));
        btnOn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnOn.setForeground(new java.awt.Color(0, 0, 0));
        btnOn.setText("ON");
        btnOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOnMouseReleased(evt);
            }
        });
        btnOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnActionPerformed(evt);
            }
        });

        btnOff.setBackground(new java.awt.Color(204, 0, 0));
        btnOff.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnOff.setForeground(new java.awt.Color(0, 0, 0));
        btnOff.setText("OFF");
        btnOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOffMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOffMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOffMouseReleased(evt);
            }
        });
        btnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOffActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mesin");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnOn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOff))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOn)
                    .addComponent(btnOff))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        btnPlusGigi.setBackground(new java.awt.Color(51, 51, 51));
        btnPlusGigi.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnPlusGigi.setForeground(new java.awt.Color(255, 255, 255));
        btnPlusGigi.setText("+");
        btnPlusGigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusGigiActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\KomangRyan\\Downloads\\pngegg.png")); // NOI18N

        btnMinusGigi.setBackground(new java.awt.Color(51, 51, 51));
        btnMinusGigi.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnMinusGigi.setForeground(new java.awt.Color(255, 255, 255));
        btnMinusGigi.setText("-");
        btnMinusGigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusGigiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPlusGigi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinusGigi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(39, 39, 39))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPlusGigi, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(btnMinusGigi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Avanza 2012");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\KomangRyan\\Downloads\\pbo avanza.png")); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\KomangRyan\\Downloads\\speedometer.png")); // NOI18N

        trem.setBackground(new java.awt.Color(204, 0, 0));
        trem.setForeground(new java.awt.Color(255, 255, 255));
        trem.setText("Rem");
        trem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tremMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tremMouseReleased(evt);
            }
        });
        trem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tremActionPerformed(evt);
            }
        });

        tgas.setBackground(new java.awt.Color(204, 0, 0));
        tgas.setForeground(new java.awt.Color(255, 255, 255));
        tgas.setText("Gas");
        tgas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tgasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tgasMouseReleased(evt);
            }
        });
        tgas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(trem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(446, Short.MAX_VALUE)
                    .addComponent(tgas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(188, 188, 188)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(trem)
                        .addGap(39, 39, 39)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(382, Short.MAX_VALUE)
                    .addComponent(tgas)
                    .addGap(236, 236, 236)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int GIGI=0;
    private void btnPlusGigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusGigiActionPerformed
        // TODO add your handling code here:
        if(lgigi.equals("N")){
            GIGI=0;
        }
        if(GIGI<=5){
            GIGI+=1;
            lgigi.setText(Integer.toString(GIGI));
            
        }
        if (GIGI == 6){
            lgigi.setText("N");
            GIGI=0;
        }
        
    }//GEN-LAST:event_btnPlusGigiActionPerformed
    void set1(JLabel a, boolean b){
        a.setText(Boolean.toString(b));
    }
    void set(JLabel a, JLabel b, JLabel c, JLabel d, JLabel e, JLabel f, boolean g){
        String isi="";
        if(g==true){
            isi="Ready";
        }
        if(g==false){
            isi="Not Ready";
        }
        a.setText(isi);
        b.setText(isi);
        c.setText(isi);
        d.setText(isi);
        e.setText(isi);
        f.setText(isi);
    }
    
    
    private void btnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOffActionPerformed
        a.matikanMesin();
//        set1(lmesin,a.mesin);
        set(lmesin, lgas, lrem,lac,ltape,ltv, a.mesin);
        btnPlusGigi.setEnabled(false);
        btnMinusGigi.setEnabled(false);
        lgigi.setEnabled(false);
        tAC.setEnabled(false);
        tTape.setEnabled(false);
        tTV.setEnabled(false);
        tgas.setEnabled(false);
        trem.setEnabled(false);
        
        
//        lmesin.setText(Boolean.toString(a.mesin));
//        lgas.setText("Mati");
//        lrem.setText("Mati");
//        lac.setText("Mati");
//        ltape.setText("Mati");
//        ltv.setText("Mati");

//        jgigi.setText("");
//        jgas.setText("");
//        jrem.setText("");
//        jac.setText("");
//        jtape.setText("");
//        jtv.setText("");
 
             


    }//GEN-LAST:event_btnOffActionPerformed

    private void btnOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnActionPerformed
            // TODO add your handling code here:
        
        a.nyalakanMesin();
//        set1(lmesin, a.mesin);
        set(lmesin, lgas, lrem,lac,ltape,ltv, a.mesin);
        btnPlusGigi.setEnabled(true);
        btnMinusGigi.setEnabled(true);
        lgigi.setEnabled(true);
        tAC.setEnabled(true);
        tTape.setEnabled(true);
        tTV.setEnabled(true);
        tgas.setEnabled(true);
        trem.setEnabled(true);
        
        

//        jgigi.setEditable(true);
//        jgas.setEditable(true);
//        jrem.setEditable(true);
//        jac.setEditable(true);
//        jtape.setEditable(true);
//        jtv.setEditable(true);
    }//GEN-LAST:event_btnOnActionPerformed
    void Tombol(JLabel a, boolean g){
        String isi="";
        if(g==true){
            isi="Nyala";
        }
        if(g==false){
            isi="Mati";
        }
        a.setText(isi);
    }
    private void btnOnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOnMouseEntered
        // TODO add your handling code here:
        btnOn.setBackground(new Color(102,255,102));
    }//GEN-LAST:event_btnOnMouseEntered

    private void btnOnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOnMouseExited
        // TODO add your handling code here:
        btnOn.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_btnOnMouseExited

    private void btnOnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOnMousePressed
        // TODO add your handling code here:
        btnOn.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_btnOnMousePressed

    private void btnOnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOnMouseReleased
        // TODO add your handling code here:
        btnOn.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_btnOnMouseReleased

    private void btnOffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffMouseEntered
        // TODO add your handling code here:
        btnOff.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_btnOffMouseEntered

    private void btnOffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffMouseExited
        // TODO add your handling code here:
        btnOff.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_btnOffMouseExited

    private void btnOffMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffMousePressed
        // TODO add your handling code here:
        btnOff.setBackground(new Color(102,0,0));
    }//GEN-LAST:event_btnOffMousePressed

    private void btnOffMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffMouseReleased
        // TODO add your handling code here:
        btnOff.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_btnOffMouseReleased
//    void ONOFF(JToggleButton btn, boolean bol){
//    if(btn.isSelected()){
//        a.nyalakanAC();
//        String status = "";
//            status ="Nyala";
//        lac.setText(status);
//    }
//    else if(btn.isSelected()){
//        a.nyalakantape();
//        ltape.setText(Boolean.toString(a.tape));
//    }
//    }
    
    
    private void tACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tACActionPerformed
    
    
     // TODO add your handling code here:
    }//GEN-LAST:event_tACActionPerformed

    private void tACMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tACMousePressed
        // TODO add your handling code here:
        if(tAC.isSelected()){
        a.nyalakanAC();
        lac.setText(Boolean.toString(a.ac));
        tAC.setBackground(new Color(204,106,0));
        }  
        Tombol(lac,a.ac);
    }//GEN-LAST:event_tACMousePressed

    private void tACMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tACMouseReleased
        // TODO add your handling code here:
        if(tAC.isSelected()){
            a.matikanAC();
        
        lac.setText(Boolean.toString(a.ac));
        tAC.setBackground(new Color(204,0,0));
    }
        Tombol(lac,a.ac);
        
    }//GEN-LAST:event_tACMouseReleased

    private void tTapeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTapeMousePressed
        // TODO add your handling code here:
           if(tTape.isSelected()){
        a.nyalakantape();
        ltape.setText(Boolean.toString(a.tape));
        tTape.setBackground(new Color(204,106,0));
    }  
           Tombol(ltape,a.tape);
    }//GEN-LAST:event_tTapeMousePressed

    private void tTapeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTapeMouseReleased
        // TODO add your handling code here:
        if(tTape.isSelected()){
        a.matikanTape();
        ltape.setText(Boolean.toString(a.tape));
        tTape.setBackground(new Color(204,0,0));
        }
        Tombol(ltape,a.tape);
    }//GEN-LAST:event_tTapeMouseReleased

    private void tTapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTapeActionPerformed

    private void tTVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTVMousePressed
        // TODO add your handling code here:
         if(tTV.isSelected()){
        a.nyalakanTV();
        ltv.setText(Boolean.toString(a.tv));
        tTV.setBackground(new Color(204,106,0));
    }  
         Tombol(ltv,a.tv);
    }//GEN-LAST:event_tTVMousePressed

    private void tTVMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTVMouseReleased
        // TODO add your handling code here:
        if(tTV.isSelected()){
        a.matikanTV();
        ltv.setText(Boolean.toString(a.tv));
        tTV.setBackground(new Color(204,0,0));
        }
        Tombol(ltv,a.tv);
    }//GEN-LAST:event_tTVMouseReleased

    private void tTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTVActionPerformed

    private void btnMinusGigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusGigiActionPerformed
        // TODO add your handling code here:
          if(lgigi.equals("N")){
            GIGI=6;
        }
        if(GIGI>0 ){
            GIGI-=1;
            lgigi.setText(Integer.toString(GIGI));
            
        }
        if (GIGI == 0){
            lgigi.setText("N");
            GIGI=6;
        }
    }//GEN-LAST:event_btnMinusGigiActionPerformed

    private void tremMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tremMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tremMousePressed

    private void tremMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tremMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tremMouseReleased

    private void tremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tremActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tremActionPerformed

    private void tgasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgasMousePressed

    private void tgasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgasMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tgasMouseReleased

    private void tgasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgasActionPerformed
    
        
        
    
                                     
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinusGigi;
    private javax.swing.JButton btnOff;
    private javax.swing.JButton btnOn;
    private javax.swing.JButton btnPlusGigi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lac;
    private javax.swing.JLabel lgas;
    private javax.swing.JLabel lgigi;
    private javax.swing.JLabel lmesin;
    private javax.swing.JLabel lrem;
    private javax.swing.JLabel ltape;
    private javax.swing.JLabel ltv;
    private javax.swing.JToggleButton tAC;
    private javax.swing.JToggleButton tTV;
    private javax.swing.JToggleButton tTape;
    private javax.swing.JToggleButton tgas;
    private javax.swing.JToggleButton trem;
    // End of variables declaration//GEN-END:variables
}
