/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasGUI;

/**
 *
 * @author KomangRyan
 */
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;


public class formMobilPolisi extends javax.swing.JFrame {
     mobilPolisi a = new mobilPolisi();
     
              

  
    
    /**
     * Creates new form formMobil
     */
    public formMobilPolisi() {
        initComponents();
         Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width/2-this.getSize().width/2;
        int y = layar.height/2-this.getSize().height/2;
        this.setLocation(x,y);
        setTitle("Mobil Polisi");
    btnOff.doClick();
    lgigi.setText("N");
    lspeed.setText("0"+" KM/H");
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lmesin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lac = new javax.swing.JLabel();
        ltape = new javax.swing.JLabel();
        ltv = new javax.swing.JLabel();
        tAC = new javax.swing.JToggleButton();
        tTape = new javax.swing.JToggleButton();
        tTV = new javax.swing.JToggleButton();
        jLabel19 = new javax.swing.JLabel();
        lht = new javax.swing.JLabel();
        tht = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        btnOn = new javax.swing.JButton();
        btnOff = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnPlusGigi = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnMinusGigi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tgas = new javax.swing.JToggleButton();
        trem = new javax.swing.JToggleButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lrem = new javax.swing.JLabel();
        lgas = new javax.swing.JLabel();
        lnomor = new javax.swing.JLabel();
        cjenis = new javax.swing.JComboBox<>();
        btnshow = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lgigi = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lspeed = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnOnSirine = new javax.swing.JButton();
        btnOffSirine = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        lsirine = new javax.swing.JLabel();
        btnchange = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setForeground(new java.awt.Color(0, 51, 153));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Status Mesin");

        lmesin.setBackground(new java.awt.Color(255, 255, 255));
        lmesin.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        lmesin.setForeground(new java.awt.Color(0, 255, 0));
        lmesin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lmesin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Coding OOP\\interfaceGui\\Gambar PBO Mobil\\mesin.png")); // NOI18N
        jLabel4.setText("Rem  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lmesin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lmesin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("AC ");

        jLabel6.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tape ");

        jLabel7.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TV ");

        lac.setBackground(new java.awt.Color(255, 255, 255));
        lac.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        lac.setForeground(new java.awt.Color(0, 255, 0));
        lac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lac.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ltape.setBackground(new java.awt.Color(255, 255, 255));
        ltape.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        ltape.setForeground(new java.awt.Color(0, 255, 0));
        ltape.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltape.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ltv.setBackground(new java.awt.Color(255, 255, 255));
        ltv.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        ltv.setForeground(new java.awt.Color(0, 255, 0));
        ltv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltv.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tAC.setBackground(new java.awt.Color(204, 0, 0));
        tAC.setForeground(new java.awt.Color(255, 255, 255));
        tAC.setText("I      O");
        tAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tACActionPerformed(evt);
            }
        });

        tTape.setBackground(new java.awt.Color(204, 0, 0));
        tTape.setForeground(new java.awt.Color(255, 255, 255));
        tTape.setText("I      O");
        tTape.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tTapeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tTapeMouseReleased(evt);
            }
        });
        tTape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTapeActionPerformed(evt);
            }
        });

        tTV.setBackground(new java.awt.Color(204, 0, 0));
        tTV.setForeground(new java.awt.Color(255, 255, 255));
        tTV.setText("I      O");
        tTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tTVMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tTVMouseReleased(evt);
            }
        });
        tTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTVActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("HT");

        lht.setBackground(new java.awt.Color(255, 255, 255));
        lht.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        lht.setForeground(new java.awt.Color(0, 255, 0));
        lht.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lht.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tht.setBackground(new java.awt.Color(204, 0, 0));
        tht.setForeground(new java.awt.Color(255, 255, 255));
        tht.setText("I      O");
        tht.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                thtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                thtMouseReleased(evt);
            }
        });
        tht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lht, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tht))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ltv, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ltape, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lac, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tTape)
                            .addComponent(tAC)
                            .addComponent(tTV))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lac, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tAC)
                    .addComponent(jLabel5))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ltape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tTape)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ltv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(lht, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tht)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        btnOn.setBackground(new java.awt.Color(0, 153, 0));
        btnOn.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnOn.setForeground(new java.awt.Color(255, 255, 255));
        btnOn.setText("ON  ");
        btnOn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOnMouseReleased(evt);
            }
        });
        btnOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnActionPerformed(evt);
            }
        });

        btnOff.setBackground(new java.awt.Color(204, 0, 0));
        btnOff.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnOff.setForeground(new java.awt.Color(255, 255, 255));
        btnOff.setText("OFF");
        btnOff.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOffMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOffMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOffMouseReleased(evt);
            }
        });
        btnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOffActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mesin");

        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\Coding OOP\\interfaceGui\\Gambar PBO Mobil\\kisspng-car-honda-button-engine-ignition-switch-button-white-5b49eb48112ae8.2860314015315710160703.png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnOn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        btnPlusGigi.setBackground(new java.awt.Color(51, 51, 51));
        btnPlusGigi.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnPlusGigi.setForeground(new java.awt.Color(255, 255, 255));
        btnPlusGigi.setText("+");
        btnPlusGigi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPlusGigiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPlusGigiMouseExited(evt);
            }
        });
        btnPlusGigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusGigiActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\Coding OOP\\interfaceGui\\Gambar PBO Mobil\\gigimobil.png")); // NOI18N

        btnMinusGigi.setBackground(new java.awt.Color(51, 51, 51));
        btnMinusGigi.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnMinusGigi.setForeground(new java.awt.Color(255, 255, 255));
        btnMinusGigi.setText("–");
        btnMinusGigi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinusGigiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinusGigiMouseExited(evt);
            }
        });
        btnMinusGigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusGigiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlusGigi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinusGigi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(39, 39, 39))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMinusGigi, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(btnPlusGigi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Coding OOP\\interfaceGui\\Gambar PBO Mobil\\polisi.png")); // NOI18N

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        tgas.setBackground(new java.awt.Color(51, 51, 51));
        tgas.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        tgas.setForeground(new java.awt.Color(255, 255, 255));
        tgas.setText("|||");
        tgas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        tgas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tgasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tgasMouseReleased(evt);
            }
        });
        tgas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgasActionPerformed(evt);
            }
        });

        trem.setBackground(new java.awt.Color(51, 51, 51));
        trem.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        trem.setForeground(new java.awt.Color(255, 255, 255));
        trem.setText("OOO");
        trem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        trem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tremMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tremMouseReleased(evt);
            }
        });
        trem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tremActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Rem");

        jLabel17.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gas");

        lrem.setBackground(new java.awt.Color(255, 255, 255));
        lrem.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        lrem.setForeground(new java.awt.Color(0, 255, 0));
        lrem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lrem.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lgas.setBackground(new java.awt.Color(255, 255, 255));
        lgas.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        lgas.setForeground(new java.awt.Color(0, 255, 0));
        lgas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lnomor.setBackground(new java.awt.Color(255, 255, 255));
        lnomor.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        lnomor.setForeground(new java.awt.Color(255, 0, 0));
        lnomor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnomor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cjenis.setBackground(new java.awt.Color(255, 255, 255));
        cjenis.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cjenis.setForeground(new java.awt.Color(0, 0, 0));
        cjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Mobil", "Sabhara", "Poslantas", "Brimob" }));
        cjenis.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjenisActionPerformed(evt);
            }
        });

        btnshow.setBackground(new java.awt.Color(0, 153, 0));
        btnshow.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnshow.setForeground(new java.awt.Color(255, 255, 255));
        btnshow.setText("SHOW");
        btnshow.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnshowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnshowMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnshowMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnshowMouseReleased(evt);
            }
        });
        btnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("No Inventaris");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lrem, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trem, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lgas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(lnomor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnshow, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnomor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnshow, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lrem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lgas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel13.setIcon(new javax.swing.ImageIcon("D:\\Coding OOP\\interfaceGui\\Gambar PBO Mobil\\toyota.png")); // NOI18N

        jPanel7.setBackground(new java.awt.Color(0, 51, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\Coding OOP\\interfaceGui\\Gambar PBO Mobil\\download.jpg")); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\Coding OOP\\interfaceGui\\Gambar PBO Mobil\\sirine.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gigi");

        jPanel8.setBackground(new java.awt.Color(26, 25, 25));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));

        lgigi.setBackground(new java.awt.Color(255, 255, 255));
        lgigi.setFont(new java.awt.Font("Unispace", 1, 48)); // NOI18N
        lgigi.setForeground(new java.awt.Color(255, 255, 255));
        lgigi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgigi.setText("N");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lgigi, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lgigi, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel20.setIcon(new javax.swing.ImageIcon("D:\\Coding OOP\\interfaceGui\\Gambar PBO Mobil\\ht.png")); // NOI18N

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        lspeed.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        lspeed.setForeground(new java.awt.Color(255, 255, 255));
        lspeed.setText("0 KM/H");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lspeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lspeed)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(0, 51, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        btnOnSirine.setBackground(new java.awt.Color(0, 153, 0));
        btnOnSirine.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnOnSirine.setForeground(new java.awt.Color(255, 255, 255));
        btnOnSirine.setText("ON  ");
        btnOnSirine.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnOnSirine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOnSirineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOnSirineMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOnSirineMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOnSirineMouseReleased(evt);
            }
        });
        btnOnSirine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnSirineActionPerformed(evt);
            }
        });

        btnOffSirine.setBackground(new java.awt.Color(204, 0, 0));
        btnOffSirine.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnOffSirine.setForeground(new java.awt.Color(255, 255, 255));
        btnOffSirine.setText("OFF");
        btnOffSirine.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnOffSirine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOffSirineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOffSirineMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOffSirineMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOffSirineMouseReleased(evt);
            }
        });
        btnOffSirine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOffSirineActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Sirine");

        lsirine.setBackground(new java.awt.Color(255, 255, 255));
        lsirine.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        lsirine.setForeground(new java.awt.Color(51, 102, 255));
        lsirine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lsirine.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnchange.setBackground(new java.awt.Color(255, 102, 0));
        btnchange.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnchange.setForeground(new java.awt.Color(255, 255, 255));
        btnchange.setText("Change");
        btnchange.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnchange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnchangeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnchangeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnchangeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnchangeMouseReleased(evt);
            }
        });
        btnchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(lsirine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(btnchange, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOffSirine, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOnSirine, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lsirine, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnchange, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOnSirine, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOffSirine, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        btnBack.setBackground(new java.awt.Color(255, 204, 0));
        btnBack.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 153));
        btnBack.setText("Back ");
        btnBack.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(32, 32, 32))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)))))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int GIGI=0;
    int jarak = 0;
    int speed =0;
   
    private void btnPlusGigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusGigiActionPerformed
        // TODO add your handling code here:
       if(lgigi.equals("N")){
             a.gerigi =0;
            speed = 175;
            lspeed.setText(Integer.toString(0));
        }
        if( a.gerigi<=5){
             a.gerigi+=1;
            speed+=35;
            lgigi.setText(Integer.toString( a.gerigi));
            
            lspeed.setText(Integer.toString(speed) + " KM/H");
            
        }
        if ( a.gerigi == 6 ){
            lgigi.setText("N");
            lspeed.setText(Integer.toString(0) + " KM/H");
             a.gerigi=0;
            speed=0;
        }
    }//GEN-LAST:event_btnPlusGigiActionPerformed
    void set1(JLabel a, boolean b){
        a.setText(Boolean.toString(b));
    }
    void set(JLabel a, JLabel b, JLabel c, JLabel d, JLabel e, JLabel f,JLabel g ,JLabel h, boolean i){
        String isi="";
        if(i==true){
            isi="Ready";
        }
        if(i==false){
            isi="Not Ready";
        }
        a.setText(isi);
        b.setText(isi);
        c.setText(isi);
        d.setText(isi);
        e.setText(isi);
        f.setText(isi);
        g.setText(isi);
        h.setText(isi);
        
        
        
    }
    
        void Tombol(JLabel a, boolean g){
        String isi="";
        if(g==true){                            // tombol mengambil nilai label true atau false
            isi="Nyala";
        }
        if(g==false){
            isi="Mati";
        }
        a.setText(isi);
    }//    void ONOFF(JToggleButton btn, boolean bol){
//    if(btn.isSelected()){
//        a.nyalakanAC();
//        String status = "";
//            status ="Nyala";
//        lac.setText(status);
//    }
//    else if(btn.isSelected()){
//        a.nyalakantape();
//        ltape.setText(Boolean.toString(a.tape));
//    }
//    }
    
    
    private void tACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tACActionPerformed
        if(tAC.isSelected()){
        a.nyalakanAC();
        lac.setText(Boolean.toString(a.ac));
        tAC.setBackground(new Color(204,106,0));
        
        Tombol(lac,a.ac);}
        else{
            
        a.matikanAC();
        
        lac.setText(Boolean.toString(a.ac));
        tAC.setBackground(new Color(204,0,0));
    
        Tombol(lac,a.ac); 
        }
//        if(tAC.getAction().equals(true)){
//            
//        }
    }//GEN-LAST:event_tACActionPerformed

    private void tTapeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTapeMousePressed
        // TODO add your handling code here:
//           if(tTape.isSelected()){
//        a.nyalakantape();
//        ltape.setText(Boolean.toString(a.tape));
//        tTape.setBackground(new Color(204,106,0));
//    }  
//           Tombol(ltape,a.tape);
    }//GEN-LAST:event_tTapeMousePressed

    private void tTapeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTapeMouseReleased
        // TODO add your handling code here:
//        if(tTape.isSelected()){
//        a.matikanTape();
//        ltape.setText(Boolean.toString(a.tape));
//        tTape.setBackground(new Color(204,0,0));
//        }
//        Tombol(ltape,a.tape);
    }//GEN-LAST:event_tTapeMouseReleased

    private void tTapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTapeActionPerformed
    if(tTape.isSelected()){
        a.nyalakantape();
        ltape.setText(Boolean.toString(a.tape));
        tTape.setBackground(new Color(204,106,0));
    
           Tombol(ltape,a.tape);
    } else {
        a.matikanTape();
        ltape.setText(Boolean.toString(a.tape));
        tTape.setBackground(new Color(204,0,0));
        
        Tombol(ltape,a.tape);
    }
    
    }//GEN-LAST:event_tTapeActionPerformed

    private void tTVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTVMousePressed
        // TODO add your handling code here:
//         if(tTV.isSelected()){
//        a.nyalakanTV();
//        ltv.setText(Boolean.toString(a.tv));
//        tTV.setBackground(new Color(204,106,0));
//    }  
//         Tombol(ltv,a.tv);
    }//GEN-LAST:event_tTVMousePressed

    private void tTVMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTVMouseReleased
        // TODO add your handling code here:
//        if(tTV.isSelected()){
//        a.matikanTV();
//        ltv.setText(Boolean.toString(a.tv));
//        tTV.setBackground(new Color(204,0,0));
//        }
//        Tombol(ltv,a.tv);
    }//GEN-LAST:event_tTVMouseReleased

    private void tTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTVActionPerformed
     if(tTV.isSelected()){
        a.nyalakanTV();
        ltv.setText(Boolean.toString(a.tv));
        tTV.setBackground(new Color(204,106,0));
    
         Tombol(ltv,a.tv); 
     }
     else{a.matikanTV();
        ltv.setText(Boolean.toString(a.tv));
        tTV.setBackground(new Color(204,0,0));
        
        Tombol(ltv,a.tv);
    }
// TODO add your handling code here:
    }//GEN-LAST:event_tTVActionPerformed

    private void btnMinusGigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusGigiActionPerformed
        // TODO add your handling code here:
        
        if(lgigi.equals("N")){
             a.gerigi=6;
            speed = 210;
            lspeed.setText(Integer.toString(0)+ " KM/H");
            
        }
        if( a.gerigi>0 ){
             a.gerigi-=1;
            speed-=35;
            lgigi.setText(Integer.toString( a.gerigi));
            lspeed.setText(Integer.toString(speed)+ " KM/H");
            
        }
        if ( a.gerigi == 0 && speed == 0){
            lgigi.setText("N");
             a.gerigi=6;
            speed = 210;
             lspeed.setText(Integer.toString(0)+ " KM/H");
            
            
        }
    }//GEN-LAST:event_btnMinusGigiActionPerformed

    private void tremMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tremMousePressed
        // TODO add your handling code here:
           trem.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_tremMousePressed

    private void tremMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tremMouseReleased
        // TODO add your handling code here:
         trem.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_tremMouseReleased

    private void tremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tremActionPerformed
        // TODO add your handling code here:
         if(trem.isSelected()){
             tgas.setEnabled(false);
        a.tekanRem();
        lrem.setText(Boolean.toString(a.rem));
        
        
       
    
         Tombol(lrem,a.rem); 
       lspeed.setText(Integer.toString(0)); 
       lgigi.setText("N"); 
       btnPlusGigi.setEnabled(false);
       btnMinusGigi.setEnabled(false);
      
     }
        else{
              tgas.setEnabled(true);
            a.matikanMesin();
             Tombol(lrem,a.mesin);
              btnPlusGigi.setEnabled(true);
              btnMinusGigi.setEnabled(true);
        }
      
    }//GEN-LAST:event_tremActionPerformed

    private void tgasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgasMousePressed
        // TODO add your handling code here:
//          if(tAC.isSelected()){
             tgas.setBackground(new Color(153,153,255));
//          
//          }
    }//GEN-LAST:event_tgasMousePressed

    private void tgasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgasMouseReleased
        // TODO add your handling code here:
//          if(tAC.isSelected()){
          tgas.setBackground(new Color(51,51,51));
//          }
    }//GEN-LAST:event_tgasMouseReleased

    private void tgasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgasActionPerformed
        // TODO add your handling code here:
        
        if(tgas.isSelected()){
        trem.setEnabled(false);
        a.tekanGas();
        lgas.setText(Boolean.toString(a.gas));
       
    
         Tombol(lgas,a.gas); 
     }
        else{
             trem.setEnabled(true);
            a.matikanMesin();
             Tombol(lgas,a.mesin);
        }
      
        
       
    
    }//GEN-LAST:event_tgasActionPerformed

    private void btnPlusGigiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusGigiMouseEntered
        // TODO add your handling code here:
        btnPlusGigi.setBackground(new Color(0,255,0));
    }//GEN-LAST:event_btnPlusGigiMouseEntered

    private void btnPlusGigiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusGigiMouseExited
        // TODO add your handling code here:
          btnPlusGigi.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_btnPlusGigiMouseExited

    private void btnMinusGigiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusGigiMouseEntered
        // TODO add your handling code here:
        btnMinusGigi.setBackground(new Color(0,255,0));
    }//GEN-LAST:event_btnMinusGigiMouseEntered

    private void btnMinusGigiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusGigiMouseExited
        // TODO add your handling code here:
        btnMinusGigi.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_btnMinusGigiMouseExited

    private void btnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOffActionPerformed
        a.matikanMesin();
        //        set1(lmesin,a.mesin);
        set(lmesin, lgas, lrem,lac,ltape,ltv, lsirine,lht, a.mesin);

        if(a.mesin ==false){                 // mesin false keluar text mati
            String mesin ="Mati";
            lmesin.setText(mesin);
        }

        lspeed.setText(Integer.toString(0));
        lgigi.setText("N");

        btnPlusGigi.setEnabled(false);
        btnMinusGigi.setEnabled(false); 
        btnOnSirine.setEnabled(false);   
         btnOffSirine.setEnabled(false);
         btnchange.setEnabled(false);   // kalau pencet off semuanya enable false
        lgigi.setEnabled(false);
        tAC.setEnabled(false);
        tTape.setEnabled(false);
        tTV.setEnabled(false);
        tht.setEnabled(false);
        tgas.setEnabled(false);
        trem.setEnabled(false);
        lspeed.setEnabled(false);
        cjenis.setEnabled(false);
        btnshow.setEnabled(false);        

    }//GEN-LAST:event_btnOffActionPerformed

    private void btnOffMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffMouseReleased
        // TODO add your handling code here:
        btnOff.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_btnOffMouseReleased

    private void btnOffMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffMousePressed
        // TODO add your handling code here:
        btnOff.setBackground(new Color(102,0,0));
    }//GEN-LAST:event_btnOffMousePressed

    private void btnOffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffMouseExited
        // TODO add your handling code here:
        btnOff.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_btnOffMouseExited

    private void btnOffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffMouseEntered
        // TODO add your handling code here:
        btnOff.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_btnOffMouseEntered

    private void btnOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnActionPerformed
        // TODO add your handling code here:

        a.nyalakanMesin();
        //        set1(lmesin, a.mesin);
        set(lmesin, lgas, lrem,lac,ltape,ltv,lsirine,lht, a.mesin);

        String mesin ="";
        if(a.mesin ==true){
            mesin ="Nyala";                // mesin true keluar nyala
            lmesin.setText(mesin);
        }
        btnPlusGigi.setEnabled(true);
        btnMinusGigi.setEnabled(true);
        btnOnSirine.setEnabled(true);   
         btnOffSirine.setEnabled(true);
         btnchange.setEnabled(true);   
         

        lgigi.setEnabled(true);
        tAC.setEnabled(true);
        tTape.setEnabled(true);
        tTV.setEnabled(true);
        tgas.setEnabled(true);
        trem.setEnabled(true);
        tht.setEnabled(true);
        lspeed.setEnabled(true);
        cjenis.setEnabled(true);
        btnshow.setEnabled(true);
       

        //        jgigi.setEditable(true);
        //        jgas.setEditable(true);
        //        jrem.setEditable(true);
        //        jac.setEditable(true);
        //        jtape.setEditable(true);
        //        jtv.setEditable(true);
    }//GEN-LAST:event_btnOnActionPerformed

    private void btnOnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOnMouseReleased
        // TODO add your handling code here:
        btnOn.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_btnOnMouseReleased

    private void btnOnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOnMousePressed
        // TODO add your handling code here:
        btnOn.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_btnOnMousePressed

    private void btnOnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOnMouseExited
        // TODO add your handling code here:
        btnOn.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_btnOnMouseExited

    private void btnOnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOnMouseEntered
        // TODO add your handling code here:
        btnOn.setBackground(new Color(102,255,102));
    }//GEN-LAST:event_btnOnMouseEntered

    private void btnOffSirineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffSirineMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOffSirineMouseEntered

    private void btnOffSirineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffSirineMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOffSirineMouseExited

    private void btnOffSirineMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffSirineMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOffSirineMousePressed

    private void btnOffSirineMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffSirineMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOffSirineMouseReleased

    private void btnOffSirineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOffSirineActionPerformed
        // TODO add your handling code here:
          a.matikanSirine();
         String sirine ="";
        if(a.sirine ==false){
            sirine ="Mati";                // mesin true keluar nyala
            lsirine.setText(sirine);
        }
    }//GEN-LAST:event_btnOffSirineActionPerformed

    private void btnOnSirineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnSirineActionPerformed
        // TODO add your handling code here:
        a.nyalakanSirine();
         String sirine ="";
        if(a.sirine ==true){
            sirine ="Nyala";                // mesin true keluar nyala
            lsirine.setText(sirine);
        }
        
        
    }//GEN-LAST:event_btnOnSirineActionPerformed

    private void btnOnSirineMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOnSirineMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOnSirineMouseReleased

    private void btnOnSirineMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOnSirineMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOnSirineMousePressed

    private void btnOnSirineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOnSirineMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOnSirineMouseExited

    private void btnOnSirineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOnSirineMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOnSirineMouseEntered

    private void btnchangeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnchangeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnchangeMouseEntered

    private void btnchangeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnchangeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnchangeMouseExited

    private void btnchangeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnchangeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnchangeMousePressed

    private void btnchangeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnchangeMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnchangeMouseReleased

    private void btnchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangeActionPerformed
        // TODO add your handling code here:
        a.gantiSuaraSirine();
        lsirine.setText("* BEEP * SUARA DIGANTI *");
    }//GEN-LAST:event_btnchangeActionPerformed

    private void thtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_thtMousePressed

    private void thtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thtMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_thtMouseReleased

    private void thtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thtActionPerformed
        // TODO add your handling code here:
          if(tht.isSelected()){
        a.nyalakanHT();
        lht.setText(Boolean.toString(a.HT));
        tht.setBackground(new Color(204,106,0));
    
         Tombol(lht,a.HT); 
     }
     else{a.matikanHT();
        lht.setText(Boolean.toString(a.HT));
        tht.setBackground(new Color(204,0,0));
        
        Tombol(lht,a.HT);
    }
    }//GEN-LAST:event_thtActionPerformed

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        btnBack.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Home main = new Home();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjenisActionPerformed

        // TODO add your handling code here:
        if(cjenis.getSelectedItem().equals("Pilih Mobil")){
            lnomor.setText(" --- ");
        }
    }//GEN-LAST:event_cjenisActionPerformed

    private void btnshowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnshowMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnshowMouseEntered

    private void btnshowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnshowMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnshowMouseExited

    private void btnshowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnshowMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnshowMousePressed

    private void btnshowMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnshowMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnshowMouseReleased

    private void btnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowActionPerformed
        // TODO add your handling code here:
        if(cjenis.getSelectedItem().equals("Sabhara")){
           a.setNomorInv(1);
            lnomor.setText("POLRI.00"+a.getNomorInv());


        }
        
        if(cjenis.getSelectedItem().equals("Poslantas")){
             a.setNomorInv(2);
            lnomor.setText("POLRI.00"+a.getNomorInv());


        }

        if(cjenis.getSelectedItem().equals("Brimob")){
             a.setNomorInv(3);
            lnomor.setText("POLRI.00"+a.getNomorInv());



        }
        
         
    }//GEN-LAST:event_btnshowActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMobilPolisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMobilPolisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMobilPolisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMobilPolisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMobilPolisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMinusGigi;
    private javax.swing.JButton btnOff;
    private javax.swing.JButton btnOffSirine;
    private javax.swing.JButton btnOn;
    private javax.swing.JButton btnOnSirine;
    private javax.swing.JButton btnPlusGigi;
    private javax.swing.JButton btnchange;
    private javax.swing.JButton btnshow;
    private javax.swing.JComboBox<String> cjenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lac;
    private javax.swing.JLabel lgas;
    private javax.swing.JLabel lgigi;
    private javax.swing.JLabel lht;
    private javax.swing.JLabel lmesin;
    private javax.swing.JLabel lnomor;
    private javax.swing.JLabel lrem;
    private javax.swing.JLabel lsirine;
    private javax.swing.JLabel lspeed;
    private javax.swing.JLabel ltape;
    private javax.swing.JLabel ltv;
    private javax.swing.JToggleButton tAC;
    private javax.swing.JToggleButton tTV;
    private javax.swing.JToggleButton tTape;
    private javax.swing.JToggleButton tgas;
    private javax.swing.JToggleButton tht;
    private javax.swing.JToggleButton trem;
    // End of variables declaration//GEN-END:variables
}
