/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasGUI;

/**
 *
 * @author KomangRyan
 */

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Color;
import javax.swing.*;
import javax.swing.JOptionPane;




public class Home extends javax.swing.JFrame {

     
         

  
    
    /**
     * Creates new form formMobil
     */
    public Home() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width/2-this.getSize().width/2;
        int y = layar.height/2-this.getSize().height/2;
        this.setLocation(x,y);
        setTitle("Home GUI OOP");
        lfoto.setVisible(false);
      
   
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lfoto = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ctheme = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lkelompok = new javax.swing.JLabel();
        lnama1 = new javax.swing.JLabel();
        lnama2 = new javax.swing.JLabel();
        btnshow = new javax.swing.JButton();
        btnshow1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cframe = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setForeground(new java.awt.Color(0, 51, 153));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Coding OOP\\interfaceGui\\Gambar PBO Mobil\\gui.png")); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon("D:\\Coding OOP\\interfaceGui\\Gambar PBO Mobil\\transport.png")); // NOI18N

        lfoto.setIcon(new javax.swing.ImageIcon("D:\\Coding OOP\\interfaceGui\\Gambar PBO Mobil\\foto1.png")); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\KomangRyan\\Downloads\\Pbo mobil\\PngItem_3024786.png")); // NOI18N

        ctheme.setBackground(new java.awt.Color(255, 255, 255));
        ctheme.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        ctheme.setForeground(new java.awt.Color(0, 0, 0));
        ctheme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Dark", "Light" }));
        ctheme.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ctheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cthemeActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\KomangRyan\\Downloads\\Pbo mobil\\Car-Accessories-PNG-Images.png")); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\Coding OOP\\interfaceGui\\Gambar PBO Mobil\\theme.png")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lkelompok.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        lkelompok.setForeground(new java.awt.Color(255, 255, 255));
        lkelompok.setText("Kelompok OOP");

        lnama1.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        lnama1.setForeground(new java.awt.Color(51, 204, 0));
        lnama1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnama1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        lnama2.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        lnama2.setForeground(new java.awt.Color(51, 204, 0));
        lnama2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnama2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        btnshow.setBackground(new java.awt.Color(255, 204, 0));
        btnshow.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnshow.setForeground(new java.awt.Color(0, 0, 0));
        btnshow.setIcon(new javax.swing.ImageIcon("C:\\Users\\KomangRyan\\Downloads\\Pbo mobil\\view.png")); // NOI18N
        btnshow.setText(" Show");
        btnshow.setBorder(new javax.swing.border.MatteBorder(null));
        btnshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnshowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnshowMouseExited(evt);
            }
        });
        btnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowActionPerformed(evt);
            }
        });

        btnshow1.setBackground(new java.awt.Color(0, 153, 0));
        btnshow1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnshow1.setForeground(new java.awt.Color(0, 0, 0));
        btnshow1.setText("Clear");
        btnshow1.setBorder(new javax.swing.border.MatteBorder(null));
        btnshow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshow1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lkelompok)
                .addGap(99, 99, 99))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lnama2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnshow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnshow1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lnama1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lkelompok, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lnama1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lnama2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnshow1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnshow, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btnPlay.setBackground(new java.awt.Color(51, 204, 0));
        btnPlay.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(0, 0, 0));
        btnPlay.setIcon(new javax.swing.ImageIcon("C:\\Users\\KomangRyan\\Downloads\\Pbo mobil\\black vector play button icon_4231897.png")); // NOI18N
        btnPlay.setText("PLAY");
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPlayMouseExited(evt);
            }
        });
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon("D:\\Coding OOP\\interfaceGui\\Gambar PBO Mobil\\exit.png")); // NOI18N
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cframe.setBackground(new java.awt.Color(255, 255, 255));
        cframe.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cframe.setForeground(new java.awt.Color(0, 0, 0));
        cframe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Gui Kendaraan", "Mobil Transport", "Bus", "Mobil Pribadi", "Truk", "Mobil Negara", "Ambulance", "Mobil Polisi" }));
        cframe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cframe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cframeActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\Coding OOP\\interfaceGui\\Gambar PBO Mobil\\ig.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cframe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnPlay)
                                .addGap(58, 58, 58)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlay)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cframe, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setIcon(new javax.swing.ImageIcon("D:\\Coding OOP\\interfaceGui\\Gambar PBO Mobil\\transport-1-logo-black-and-white.png")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(43, 43, 43)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctheme, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(271, 271, 271)
                    .addComponent(jLabel21)
                    .addContainerGap(303, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8)))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel15))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(ctheme, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel12)))))
                .addGap(25, 25, 25))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(655, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
      
    private void cframeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cframeActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cframeActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
         if(cframe.getSelectedItem().equals("Pilih Gui Kendaraan")){
          JOptionPane.showMessageDialog(null, "Please Select Gui Kendaraan");
         }
         
        formBus bus = new formBus();
        
        formTruk truk = new formTruk();
        
        formMobilPolisi polisi = new  formMobilPolisi();
        
         formMobilTransport transport = new  formMobilTransport();
         
         formAmbulance ambulance = new formAmbulance();
         
         formMobilPribadi pribadi = new formMobilPribadi();
         
         formMobilNegara negara = new formMobilNegara();
         
        
      
          if(cframe.getSelectedItem().equals("Bus")){
               bus.setVisible(true);
               dispose();
               
          }
             if(cframe.getSelectedItem().equals("Truk")){
               truk.setVisible(true);
                dispose();
              
          }
          
             if(cframe.getSelectedItem().equals("Mobil Polisi")){
               polisi.setVisible(true);
                dispose();
               
          }
              if(cframe.getSelectedItem().equals("Mobil Transport")){
               transport.setVisible(true);
                dispose();
             
          }
               if(cframe.getSelectedItem().equals("Ambulance")){
               ambulance.setVisible(true);
                dispose();
          }
                if(cframe.getSelectedItem().equals("Mobil Pribadi")){
               pribadi.setVisible(true);
                dispose();
              
          }
                 if(cframe.getSelectedItem().equals("Mobil Negara")){
               negara.setVisible(true);
                dispose();
               
          }
           

    }//GEN-LAST:event_btnPlayActionPerformed

    private void cthemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cthemeActionPerformed
        // TODO add your handling code here:
        
         if(ctheme.getSelectedItem().equals("Default")){
        jPanel5.setBackground(new Color(0,51,102));
        jPanel1.setBackground(new Color(0,51,102));
        jPanel2.setBackground(new Color(0,51,102));
        lkelompok.setForeground(Color.WHITE);
         }
        if(ctheme.getSelectedItem().equals("Light")){
        jPanel5.setBackground(Color.WHITE);
        jPanel1.setBackground(Color.WHITE);
        jPanel2.setBackground(Color.WHITE);
         lkelompok.setForeground(Color.BLACK);
        }
         if(ctheme.getSelectedItem().equals("Dark")){
        jPanel5.setBackground(new Color (0,0,20));
        jPanel1.setBackground(new Color (0,0,20));
        jPanel2.setBackground(new Color (0,0,20));
        lkelompok.setForeground(Color.WHITE);
       
         }
    }//GEN-LAST:event_cthemeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null,"Do you want to exit","Keluar",JOptionPane.OK_CANCEL_OPTION);
        if(answer == JOptionPane.OK_OPTION){
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowActionPerformed
        // TODO add your handling code here:
        lnama1.setText("Komang Ryandhi Suandita");
         lnama2.setText("Radityo Ar Rasyid");
         lfoto.setVisible(true);
        
    }//GEN-LAST:event_btnshowActionPerformed

    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayMouseClicked

    private void btnPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseEntered
        // TODO add your handling code here:
        btnPlay.setBackground(new Color(102,255,102));
    }//GEN-LAST:event_btnPlayMouseEntered

    private void btnshow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshow1ActionPerformed
        // TODO add your handling code here:
        lnama1.setText("");
         lnama2.setText("");
         lfoto.setVisible(false);
    }//GEN-LAST:event_btnshow1ActionPerformed

    private void btnPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseExited
        // TODO add your handling code here:
            btnPlay.setBackground(new Color(51,204,0));
    }//GEN-LAST:event_btnPlayMouseExited

    private void btnshowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnshowMouseEntered
        // TODO add your handling code here:
        btnshow.setBackground(new Color(255,255,102));
    }//GEN-LAST:event_btnshowMouseEntered

    private void btnshowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnshowMouseExited
        // TODO add your handling code here:
        btnshow.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_btnshowMouseExited
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home home = new Home();
                home.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnshow;
    private javax.swing.JButton btnshow1;
    private javax.swing.JComboBox<String> cframe;
    private javax.swing.JComboBox<String> ctheme;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lfoto;
    private javax.swing.JLabel lkelompok;
    private javax.swing.JLabel lnama1;
    private javax.swing.JLabel lnama2;
    // End of variables declaration//GEN-END:variables
}
